require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'WheresMyOrder' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'WheresMyOrderTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

   # React Native
   rn_path = '../node_modules/react-native'
   rn_maps_path = '../node_modules/react-native-maps'
 
   

   pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
   pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
   pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
   
   # Required by Google Map, ignore if you use Apple Map
   pod 'GoogleMaps', '3.5.0'
   pod 'Google-Maps-iOS-Utils', '2.1.0'
   pod 'GoogleUtilities', '5.3.7'
   pod 'GoogleAppMeasurement', '5.4'
 
   pod 'react-native-maps', path: rn_maps_path
   pod 'react-native-google-maps', path: rn_maps_path # <~~ if you need GoogleMaps support on iOS


end

target 'WheresMyOrder-tvOS' do
  # Pods for WheresMyOrder-tvOS

  target 'WheresMyOrder-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == "react-native-google-maps"
          target.build_configurations.each do |config|
              config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
          end
      end
      if target.name == "React"
        target.remove_from_project
      end
  end
end